name: CI to ECR + GitOps commit

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}
        run: |
          TAG="${GITHUB_SHA::7}"
          docker build -t "$ECR_REPO_URI:$TAG" .
          docker push "$ECR_REPO_URI:$TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Checkout Repo2 which has ArgoCD installed and K8s deployment files
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO2 }}
          token: ${{ secrets.GITHUB_PAT }}
          path: k8s

      - name: Update deployment image tag in Repo2
        env:
          ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}
        run: |
          cd k8s
          # replace entire image line safely
          sed -i "s|^\(\s*image:\s*\).*|\1$ECR_REPO_URI:${TAG}|" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${TAG}" || echo "No changes"
          git push
